### ISSUE TITLE
Use dataclasses (or `typing.NamedTuple`) once Python 3-only

### ISSUE THREAD

**Issue by Eric-Arellano** [pantsbuild/pex#1041]
`collections.namedtuple` does not work with MyPy. We cannot use `typing.NamedTuple` because it's Python 3-only. So, we temporarily use our own classes.

Once we require Python 3 to run Pex, we can go back to either dataclasses or `typing.NamedTuple`.

**Comment by cosmicexplorer** [comment]
I like `@dataclass`es a lot, especially because they already accept a wide range of configuration, which may incorporate even more features in later python versions! This is what cleared my concern entirely about using them in pants vs the homegrown `datatype` -- it's something that won't cause churn with structs that many people will be editing over time! We also have code in pants to draw from to ensure we write pythonic code (or at least, pants-pythonic code).
 
Being able to switch on/off whether fields are frozen is a really nicely done feature in itself. Is there a reason we might want to consider `typing.NamedTuple` instead?

**Comment by Eric-Arellano** [comment]
Superseded by https://github.com/pantsbuild/pex/pull/1234.
