### ISSUE TITLE
Can a module import of a pex from pantsbuild be exposed?

### ISSUE THREAD

**Issue by sureshjoshi** [pantsbuild/pex#1181]
I don't know which repo I should post this question.

I'm using Nginx Unit, which has an ASGI configuration for my FastAPI application. It's working fine, but I have no clue how to use it with a PEX.

I've attached it below, but the salient point is that there is a Python plugin for Nginx Unit which is looking for a "module" and a "callable". 

What this looks like now is "apigateway.main:app" similar to uvicorn or whatever other server implementation you're using. Unlike uvicorn, gunicorn, or whatever - I don't think I can package any other tool in my pex file and use PEX_SCRIPT.

Is there any suggestion on if/how I can expose a module and variable outside of the pex?

```json
{
    "listeners": {
        "*:80": {
            "pass": "routes"
        }
    },
    "routes": [
        {
            "action": {
                "pass": "applications/api"
            }
        }
    ],
    "applications": {
        "api": {
            "type": "python 3.9",
            "path": "/app",
            "module": "apigateway.main",
            "callable": "app",
            "limits": {
                "requests": 100
            },
            "processes": {}
        }
    },
    "access_log": "/var/log/access.log"
}
```

**Comment by jsirois** [comment]
I just learned about Nginx Unit Python so bear with me on this.

From what I can tell, you can only configure Nginx Unit Python by pointing to a virtualenv with `home` and adding additional `sys.path` entries with `path`: https://unit.nginx.org/configuration/#python

This is traditionally problematic with Pex since it needs to be the main entrypoint in order to setup the `sys.path` appropriately. More concretely, a PEX file's loose source contents (those added with -D) are directly importable since Python understands how to import from a zip file but its embedded third party distributions are not (these are stored in the PEX zip under `.deps/`) and must be manipulated onto the `sys.path` at runtime by the PEX `__main__.py`.

So, for a traditional PEX file, you are simply out of luck without writing a custom Nginx Unit language module that supports PEX files.

All the traditional language here is meant to segue to the recent `venv` pex tool feature released with [Pex 2.1.22](https://github.com/pantsbuild/pex/releases/tag/v2.1.22). If you build your PEX file with venv support (add `--include-tools` to the Pex command line) then you gain the ability to create a venv from your PEX file. Doing so is a one-time manual step on the target machine or image:
```
PEX_TOOLS=1 ./my.pex venv /app
```

That will create a virtual environment containing your app and its dependencies under `/app`. You can point Nginx Unit there with `home`. I've done all this over at https://github.com/jsirois/pex-issues-1181 to prove it works.

Currently Pants does not support `--include-tools` (would be an option on a `pex_binary` target), but if you can vet this solution works for you, I'm happy to file an issue over in Pants to support the flag and implement it for this week's dev release.

**Comment by sureshjoshi** [comment]
Oh sweet, thanks for the quick reply! And the example repo!

I was looking into adding .pex support to their python module as that would streamline a fair amount of my deployment, but I don't have time for it on this current project unfortunately. The classic excuse I guess. But, it looks like that might no longer be a problem :)

I'll try out your example repo in a few minutes, then I'll try to do the same on my project and will report back

**Comment by sureshjoshi** [comment]
Okay, so, your demo repo worked perfectly - no problems. 

I'm just in the middle of debugging my repo to try and figure out why I'm getting grpc modules and such. There's a good chance I packaged the pex incorrectly, as I'd never previously done it by hand (but it looks good when I unzip it). The other option is that I'm at the wrong level of nesting somewhere.

**Comment by sureshjoshi** [comment]
Okay, so it feels like Nginx isn't picking up the python version to use for some reason. I went into the container and manually was able to import apigateway, grpc, whatever else - but when I run via nginx, I'm unable to import the modules correctly.

It may have something to do with the custom Python 3.9 container I had to build for nginx for testing. 

In any case, this issue is closed as your demo shows that it CAN work - I just need to make it work for my usecase. 

Thanks!!

**Comment by sureshjoshi** [comment]
Okay, turns out I was able to get this working. I had some stale configuration with a mount in my docker compose that ended up overwriting stuff. 

Additionally, I was using `path` instead of `home` for the venv - which doesn't even remotely work. 

So yes, `--include-tools` works!

**Comment by jsirois** [comment]
Ok - Excellent. I'll spin up a Pants feature issue / implementation for that then. Pants should also support `--unzip` off the top and there might be other slags it's missing options for.
