### ISSUE TITLE
PEX_PYTHON doesn't work on Linux

### ISSUE THREAD

**Issue by igolant** [pantsbuild/pex#1261]
Hi, i am trying to change python interpreter at runtime
but variable PEX_PYTHON doesn't affect

```
$ pex --version
2.1.32

$ cat /proc/version
Linux version 4.15.0-43.generic.x86_64 (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)) #1 SMP Wed Jan 30 02:40:05 GMT+7 2019

$ pex --python-shebang='/path/not/exists' -o test.pex

$ export PEX_PYTHON=python; ./test.pex
bash: ./test.pex: /path/not/exists: bad interpreter: No such file or directory
```

**Comment by jsirois** [comment]
@igolant this is just how shebang scripts work on Unix. Before the environment variable can be read by the PEX file process, the process needs to be launched, and the OS uses the shebang line to launch the process:
1. The OS read 1st 2 bytes of the presumptive executable binary, if they are `#!` then the OS reads the rest of the line up to some maximum number of bytes to find an absolute path to an interpreter to execute.
2. The OS executes the binary discovered in step 1 passing the presumptive executable binary as the 1st argument.

You're experiencing an OS failure in step 2. At this point neither Python nor PEX have been involved.

To do what you want though, since you know the path to a python interpreter, just run:
```
/path/to/python ./test.pex
```

See [here](https://en.wikipedia.org/wiki/Shebang_(Unix)) for more info.
