### ISSUE TITLE
can't load 1st party code/packages when zip_safe=False

### ISSUE THREAD

**Issue by asherf** [pantsbuild/pex#1349]
Noticed that when trying to run a Django's `manage.py runserver` command
<img width="1164" alt="Screen Shot 2021-05-10 at 4 59 21 PM" src="https://user-images.githubusercontent.com/1268088/117738518-1388eb00-b1b1-11eb-97a1-f7345e8ac581.png">

internal link: https://github.com/toolchainlabs/toolchain/pull/9290

**Comment by jsirois** [comment]
OK - the problem goes away when the PEX file created by Pants uses `--no-strip-pex-env`. Pants provides no way to specify this option today though.

The reason this works is that `./pants run ...` executes a Pex environment assembled from an entry-point-only PEX, a PEX_PATH adjoined requirements PEX and a PEX_EXTRA_SYS_PATH adjoined set of loose source root directories. Both the PEX_PATH and PEX_EXTRA_SYS_PATH additions are wiped out by default since PEX_ env var stripping is the default. The implication, backed up by the back trace, which now makes sense, is that django executes a subprocess using sys.argv[0] which is the PEX file; thus it goes through sys scrubbing, etc all over again, but with the two critical PEX_ env vars now unset.

**Comment by jsirois** [comment]
This does not seem to be an issue for Pex to fix. It already has the knobs to make this work and Pants just needs to use them / expose them.

Moved to Pants in https://github.com/pantsbuild/pants/issues/12057. 

Thanks for pushing on this @asherf.
