### ISSUE TITLE
Reproducibility of installed wheels

### ISSUE THREAD

**Issue by stuhood** [pantsbuild/pex#1407]
Comparing two PEXes built with `2.1.44` and `--requirement` from [a lockfile](https://github.com/pantsbuild/pants/blob/d342d9e65fb6962d9c419a0cac6c2a22d9cd486a/3rdparty/python/lockfiles/user_reqs.txt), some of the contents of the PEXes were mismatched run over run: see attached diff of the `shasum`s.

[pex-reproducibility.diff.txt](https://github.com/pantsbuild/pex/files/7016552/pex-reproducibility.diff.txt)

The `PEX-INFO`, `__main__.py`, and `RECORD` differences are secondary effects of the contents having changed: the other changes look like:
* A `*.so` file... likely due to its own build not being reproducible... there is unlikely to be anything that PEX can do here.
* Generated scripts placed in the PEX file having different shebang lines:
```diff
--- lockfile-1/.deps/pytest-6.2.4-py3-none-any.whl/bin/pytest	1980-01-01 00:00:00.000000000 -0800
+++ lockfile-2/.deps/pytest-6.2.4-py3-none-any.whl/bin/pytest	1980-01-01 00:00:00.000000000 -0800
@@ -1,8 +1,8 @@
-#!/private/var/folders/bg/_r10hqp14kjcpv68yzdk5svc0000gn/T/process-executionksN0pU/.cache/pex_root/venvs/short/9cb0d755/bin/python3.7
+#!/private/var/folders/bg/_r10hqp14kjcpv68yzdk5svc0000gn/T/process-executionXjB3hx/.cache/pex_root/venvs/short/e12499a5/bin/python3.7
 # -*- coding: utf-8 -*-
 import re
 import sys
 from pytest import console_main
 if __name__ == '__main__':
     sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
     sys.exit(console_main())
```

**Comment by jsirois** [comment]
> Generated scripts placed in the PEX file having different shebang lines

Almost certainly due to the `*.so`s as well. The venv hash includes the pex hash and the pex hash includes a hash of PEX-INFO.

**Comment by jsirois** [comment]
Let me know if you agree this can be closed or if you have an idea. I don't think there is anything Pex can reasonably do here.

**Comment by jsirois** [comment]
But actually - it's worse. A shebang must be absolute and the tmp path in those shebangs is different. So Pex aside, you'd need to fix that.

**Comment by illicitonion** [comment]
Given we're building these to be portable, in known throwaway directories, it feels like we could set a fixed shebang with a flag, to `/bin/env python` or something? It's strictly better than the status quo.

**Comment by jsirois** [comment]
I'm not sure we all understand exactly the setup of the original report. I certainly don't. This is a Pex bug report but there are Pantisms in play. The PEX_ROOT for the two runs is different, for 1: `/private/var/folders/bg/_r10hqp14kjcpv68yzdk5svc0000gn/T/process-executionksN0pU/.cache/pex_root` vs `/private/var/folders/bg/_r10hqp14kjcpv68yzdk5svc0000gn/T/process-executionXjB3hx/.cache/pex_root`. The shebangs in question look like `--venv` mode shebangs. A PEX running in `--venv` mode installs itself in a venv in he PEX_ROOT and purposefully re-writes python shebangs to point to the venv interpreter just like in any other venv impl for correctness (the script has to run with the venv interpreter specifically once installed so that it can see all the venv's installed deps). So the sharp point I think is that venvs aren't portable by design. The PEX zip file is and should be reproducible. That we have automated tests for. @stuhood can you clarify the steps used to create the PEX files or venvs from those or whichever is applicable?

**Comment by jsirois** [comment]
Ok, setting Pants aside to clarify things:
```console
$ pex --version
2.1.45
$ rm -rf ~/.pex
$ pex pex -opex.pex
$ unzip -qc pex.pex .deps/pex-2.1.45-py2.py3-none-any.whl/bin/pex | head -1
#!/home/jsirois/.pex/venvs/short/1d052010/bin/python3
$ rm -rf ~/.pex pex.pex
$ pex pex -opex.pex
$ unzip -qc pex.pex .deps/pex-2.1.45-py2.py3-none-any.whl/bin/pex | head -1
#!/home/jsirois/.pex/venvs/short/1d052010/bin/python3
```
You create a PEX file and it is reproducible, but only using the same interpreter to create that pex file. That interpreter is the Pip venv PEX creates once per Pex version per PEX_ROOT:
```console
$ ls -1 /home/jsirois/.pex/venvs/short/1d052010/lib/python3.9/site-packages/
__init__.py
__main__.pyc
__pex_patched_pip__.py
__pex_patched_pip__.pyc
pip
pip-20.3.4.dist-info
pkg_resources
__pycache__
setuptools
setuptools-44.0.0.dist-info
wheel
wheel-0.36.2.dist-info
```
So that's where the `--venv` is coming from - Pex dogfood:
https://github.com/pantsbuild/pex/blob/c9ff7d965fddb533bee846cfca2d9e0ace574074/pex/pip.py#L308-L331

So now that I've answered my own confusion about @stuhood's case and the interpreter path is definitely embedded in the PEX file bin/ scripts by normal means I agree with @illicitonion - but we can instead use an invalid and ~standard shebang for this purpose of `#!python`:
https://github.com/pantsbuild/pex/blob/196b4cd5b8dd4b4af2586460530e9a777262be7d/pex/vendor/_vendored/pip/pip/_internal/operations/install/wheel.py#L111-L129

I think this works since that shebang appears on disk in three places:
1. Inside `.deps/<installed wheel dir>/bin/<python script>` in a Pex zip file.
2. Inside `PEX_ROOT/installed/wheels/<hash dirs>/<installed wheel dir>/bin/<python script>`.
3. Inside a Pex created venv either in `PEX_ROOT/venvs/...` or in a location of choice when created via `pex-tools <pex file> venv ...`.

In the case of 1, the script can't be executed anyhow. In the case of 2 the script is loose on the filesystem and executabke, but its not added to the PATH by the Pex runtime; so its also not executable in any normal sense by the user code booted by the Pex runtime except via very tight binding to Pex internals - which I think is acceptable to break as a usage. In case 3 Pex already re-writes the shebang as noted above in order to point the script's interpreter back into the venv. In that case the shebang gets reified to the correct path for the current machine and these scripts get additionally added to the PATH if requested via `--venv {prepend,append}`.

I'm liking `#!python` over `#!/usr/bin/env python` since it'll cause script execution to fail outright for someone binding to Pex internals in the 1 or 2 scenarios above. I guess if the script were executed in a CWD that happened to contain a `python` executable though, the script would start running. Perhaps?:
```console
$ head -1 test.py 
#!In_order_to_run_this_script_rebuild_your_PEX_file_with_--venv.
$ ./test.py 
bash: ./test.py: In_order_to_run_this_script_rebuild_your_PEX_file_with_--venv.: bad interpreter: No such file or directory
```

**Comment by jsirois** [comment]
It looks like we'll need to add creating the same pex with two different interpreters to the reproducibility test here to smoke this out and keep it out:
https://github.com/pantsbuild/pex/blob/81ca9a07767e95508c80cdb41701d9e123bf6497/tests/test_integration.py#L1772-L1799
