### ISSUE TITLE
Seems a Bug

### ISSUE THREAD

**Issue by rohaan2614** [pantsbuild/pex#1514]
When I run a pip install, it aborts with the following message:

```
INFO: pip is looking at multiple versions of lexnlp to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install lexnlp and lexnlp==2.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    lexnlp 2.1.0 depends on regex==2020.11.13
    datefinder-lexpredict 0.6.2.1 depends on regex==2020.7.14

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Comment by Eric-Arellano** [comment]
Hi Rohan, this is a legitimate issue coming from pip. pip can't determine which version of `regex` to use because `lexnlp` and `datefinder-lexpredict` require conflicting versions, and pip needs exactly one version.

To fix this, you'll probably need to use different versions of `lexpredict` and `datefinder-lexpredict` so that they're compatible. Are you directly installing those two requirements? What command are you running with Pex?

**Comment by jsirois** [comment]
@Eric-Arellano it looks like you have this covered. I'll assign to you to conclude as you see fit.

**Comment by rohaan2614** [comment]
Hi @Eric-Arellano ,

I was installing all dependences via the pip install lexNLP command. What should I do instead?

**Comment by jsirois** [comment]
@rohaan2614 I'm going to close this since, as @Eric-Arellano pointed out - its a Pip issue and not a Pex issue and, more importantly, since it apprears to be a LexNLP issue: https://github.com/LexPredict/lexpredict-lexnlp/issues/58
