### ISSUE TITLE
pex command failing with version error for sendgrid on macos

### ISSUE THREAD

**Issue by suriya92** [pantsbuild/pex#1530]
### Discussed in https://github.com/pantsbuild/pex/discussions/1529

<div type='discussions-op-text'>

<sup>Originally posted by **suriya92** December  7, 2021</sup>
Hi There, 
pex command is failing on macos(version:11.6,intel chip)with the following error when attempted to include sendgrid(target platform is linux)

### ERROR: Could not find a version that satisfies the requirement starkbank-ecdsa>=2.0.1 (from sendgrid)
ERROR: No matching distribution found for starkbank-ecdsa>=2.0.1

pex command: **pex.venv/bin/pex -vvvvvvvv --output-file output.zip  --manylinux=manylinux2014 --resolve-local-platforms --no-pypi --index=https://pypi.org/simple/ --resolver-version pip-2020-resolver --platform linux-x86_64-cp-38-cp38 "sendgrid==6.9.1"**
The same command works fine on Linux. Appreciate any help on resolving this.
Thanks !</div>

**Comment by Eric-Arellano** [comment]
Hey @suriya92, it looks like the library `starkbank-ecdsa` only is distributed as an sdist (source distribution), i.e. a .tar.gz file: https://pypi.org/project/starkbank-ecdsa/#files.

When you install something with Pip or Pex, it needs to convert those into `.whl` files. The easiest way to do that is by the library author distributing a pre-built wheel (a bdist). Otherwise, you have to build the wheel locally. When you build a wheel locally, you can only build for your current platform (e.g. macOS vs. Linux).

Here, you are trying to build a `linux-x86_64-cp-38-cp38` wheel for `starkbank-ecdsa` but you're doing it from macOS, which is impossible. The only reason this is working when you run from Linux is that you have the option `--resolve-local-platforms` set so that you can try to build that wheel locally - if you remove that flag and run from Linux, the build will fail.

Some of your options are:

1. Ask the library author to release wheels: https://pythonwheels.com
2. Pre-build the wheel yourself and internally host it with a server or your filesystem, then have Pex look there.
3. Give up on building from macOS

Does this make sense?

**Comment by suriya92** [comment]
Hey @Eric-Arellano Thank you for your explanation. We are building this PEX via Pants.

**Comment by jsirois** [comment]
@suriya92 I'm going to close this as an answered question since Eric's advice is accurate. If you need more explanation of those 3 alternatives, please speak up though.
