### ISSUE TITLE
Wheel platform label changing with latest pex

### ISSUE THREAD

**Issue by avadhanij6si** [pantsbuild/pex#1569]
We are currently using pex 2.1.16, and one thing we noticed on trying to upgrade to the latest pex versions is the wheel label changing for the same version of the package in the same environment. 

E,g.: 

When building a pex that contains cryptography with pex-2.1.16, I see the label formed as follows - 
`cryptography-36.0.1-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`.

When building the same wheel in the same environment, with latest pex, I see the label formed as - 
`cryptography-36.0.1-cp36-abi3-manylinux_2_24_x86_64.whl`.

The version of `glibc` hasn't changed between the two, so why did pex pick/build `2_24` vs the older `2_17`?

I believe the `--platform` option is somehow the answer, but it's unclear how to specify enough platforms without creating an issue where pip is complaining that it couldn't find a matching distribution. For example, if no platform was passed, some packages would resolve to the following label - `py2.py3-none-any`, or `cp37-cp37m-linux_x86_64`, etc. 

Edit: 

When I built a pex only for cryptography with `--platform linux-x86_64-cp-37-m`, the old wheel label returned. However, I can't install other packages because of the issue I described in the last para.

Any suggestions on getting around this problem?

**Comment by jsirois** [comment]
Sorry for the delay @avadhanij6si! WHat is the real version of your glibc? The former, the latter or neither?

For me the real version is 2.33 for example:
```
$ /lib/libc.so.6 
GNU C Library (GNU libc) release release version 2.33.
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 11.1.0.
libc ABIs: UNIQUE IFUNC ABSOLUTE
For bug reporting instructions, please see:
<https://bugs.archlinux.org/>.
```

**Comment by avadhanij6si** [comment]
Np. It is neither - 

```
$ ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.2) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by avadhanij6si** [comment]
@jsirois, just checking to see if you had a chance to look at this again.

**Comment by avadhanij6si** [comment]
@jsirois , just checking again ☝️

**Comment by jsirois** [comment]
@avadhanij6si This was undoubtedly due to an upgrade of Pex's vendored `packaging`. Let me look - but, to help motivate further research can I ask why you're asking? Are you just curious or do you actually want Pex to be picking the older manylinux version despite the fact your machine supports a newer glibc?

**Comment by jsirois** [comment]
I'd guess it was this fix in packaging: https://github.com/pypa/packaging/pull/221
That went live in packaging 20.0 and Pex upgraded from packaging 19.2 to packaging 20.4 with the Pex 2.1.21 release.

**Comment by jsirois** [comment]
@avadhanij6si I'm sorry for the huge delay on this. I saw you not directly mention a problem or error due to the change in resolving behavior which caused me to shy away from this each time I got back to my keyboard.

I'm going to close this as answered. If you need a feature in Pex to pick older manylinux wheels than your platform can actually handle or if you want a feature where Pex guarantees to never change its resolving behavior, then maybe re-open, but I'm really not seeing any way Pex could provide either of those. Definitely not the latter anyway.

**Comment by jsirois** [comment]
Ah, you do mention a problem, but it's secondary:

> I believe the --platform option is somehow the answer, but it's unclear how to specify enough platforms without creating an issue where pip is complaining that it couldn't find a matching distribution. For example, if no platform was passed, some packages would resolve to the following label - py2.py3-none-any, or cp37-cp37m-linux_x86_64, etc.

So, 1st, why do you try to "fix" the resolved cryptography wheel to be the old one (manylinux_2_17) instead of rolling with the new one (manylinux_2_24) since your machine is supposed to be compatible with both (you're glibc 2_33).

Second though, answering the question assuming you have some reason to care about _2_17 vs _2_24, you might be able to use `--complete-platform ...`. The `--complete-platform` feature is new, and this was its intended purpose, but it effectively allows you to lie about your platform compatibility. 1st see here: https://pex.readthedocs.io/en/v2.1.71/buildingpex.html#complete-platform

The idea would be to generate a `--complete-platform` json file using `pex3 interpreter inspect --markers --tags --indent 2 > platform.json` and then hand-edit that JSON file, removing all the platform tags you don't want Pex to pick when resolving wheels. Do note though that using `--platform` or `--complete-platform` both turn off the ability to resolve projects that are only available as source distributions. If you have sdists in your resolve, you'll need to pre-build a wheel for each of those, `pip wheel --wheel-dir my-wheel-dir ...sdist requirements...` is one way, and then point Pex at those wheels with `--find-links my-wheel-dir`
