### ISSUE TITLE
Support equivalent of `pip install --target=...` to export distributions and source to flat directory

### ISSUE THREAD

**Issue by huonw** [pantsbuild/pex#2110]
`pip install` has a `--target`/`-t` option that installs the requested requirements directly to a specific directory, rather than into the usual structure with `site-packages` etc. It would be nice if pexes could support this too. Currently, there's two related `PEX_TOOLS=1` commands, but neither quite do exactly this:

- `PEX_TOOLS=1 ./some-pex venv ...`: constructs the full venv structure
- `PEX_TOOLS=1 ./some-pex repository extract ...`: only exports the distributions, not the source

Motivation: Direct installation like this is handy for building artefacts for certain cases, such as FaaS platforms like Lambda: their docs recommend just splatting all dependencies into the top level of a zip file, along with whatever first party code: https://docs.aws.amazon.com/lambda/latest/dg/python-package.html#python-package-create-package-with-dependency (steps 4-6).

More discussion: https://pantsbuild.slack.com/archives/C046T6T9U/p1680247328906249

**Comment by huonw** [comment]
Looking at the code that handles this in `pip` suggests they do a 'normal' install to a temporary directory, and then move some of the files from that install into the target directory: https://github.com/pypa/pip/blob/51afe45cda2854d810d9714e3891e256b1509737/src/pip/_internal/commands/install.py#L514-L566

This would suggest to me that, for a lot of use cases, just doing a venv export and then copying out the `lib/.../site-packages` directory might be enough, without having to implement this dedicated feature?

**Comment by jsirois** [comment]
> `PEX_TOOLS=1 ./some-pex repository extract ...`: only exports the distributions, not the source
Just noting this is not true. There is a --source option that does create and export an sdist of all the 1st party PEX code with proper `install_requires` metadata such that you can just grab that sdist alone and then copy it somewhere and `pip install the-sdist.tar.gz` and get everything back (non-reproducibly of course since `install_requires` entries may not be pinned, and even if they are they will almost never include the full transitive set; so transitive deps may be unpinned).

**Comment by jsirois** [comment]
This is getting tacked on to the feature work for #1752. There will be a `--flat` (not sure of spelling yet) flag you can tack on to `pex3 venv -d right/here {--python,--platform,--complete-platform}* reqs*|--pex PEX|--lock LOCK --scope {all,deps,srcs}` to just export to a flat dir instead of a venv site packages dir.
