### ISSUE TITLE
How to use pex3 lock export with non pypi links?

### ISSUE THREAD

**Issue by zmanji** [pantsbuild/pex#2147]
I can successfully create a lockfile by running:
```
pex3 lock create -o lxml.lock --platform macosx_13_0_x86_64-cp-39-cp39 --no-allow-pip-version-fallback --pip-version 23.1.2 --resolver-version pip-2020-resolver --find-links 'https://zmanji.github.io/lxml-macos-wheel-builder/' lxml
```

I can successfully export this lock file to pip format by running:
```
pex3 lock export lxml.lock
```

The output is:
```
lxml==4.9.2 \
  --hash=sha256:d9ac0c02be96069ebf052c5a45b13feec487b5f31b6f071ae3acc728e7047d1a
```

However placing the above in `requirements.txt` and running `pip install -r requirements.txt` results in
```
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
```

This is because pip will fetch `lxml-4.9.2.tar.gz` from pypi for `macosx_13_0_x86_64-cp-39-cp39` and will not look at my custom find links url.

The only work around I see is to remember the resolver options passed to pex and pass them to pip again. 

I tried another work around which was to build a pex from the lockfile and then extract the wheels to a local directory to pass to pip but the extracted wheels have a different checksum than what was recorded in the lockfile.

What is the recommended to get pip to consume a lockfile that references a custom url?

**Comment by jsirois** [comment]
@zmanji Are you not also passing `--find-links https://zmanji.github.io/lxml-macos-wheel-builder/` to Pip?

**Comment by zmanji** [comment]
> @zmanji Are you not also passing `--find-links https://zmanji.github.io/lxml-macos-wheel-builder/` to Pip? And are you using the same version of Pip (23.1.2)? Pip has made it clear that the precedence of --indexes and --find-links consumption is totally undefined and subject to change. And it has in fact apparently changed over time.

I am not passing the `--find-links` argument but I am using the same version of pip as what was passed to pex. Is the recommended way to use the exported lock is to pass the same resolver arguments to pip and pex? 

I currently don't record the arguments to pex that formed the lock file but I can do that and pass the same values to pip later. Is that the suggested way?

**Comment by jsirois** [comment]
@zmanji it's not really the "suggested" way - its the only way. I thought this much would be obvious since that's just how you use Pip, but I can maybe try to do better. Right now the default and only format is requirements file. Pip supports embedding _some_ arguments like --find-links in a requirements file - see: https://pip.pypa.io/en/stable/reference/requirements-file-format/#supported-options

Would it make more sense if Pex exported all applicable knobs you sent it as the equivalent knobs there?
Alternatively I could imagine a new export format that exports a script, say, that encodes everything needed to run Pip as close to equivalently as how Pex runs it. I'm not super fond of this though since it immediately gets tangled: can I assume bash? ... etc.

**Comment by jsirois** [comment]
I will note that a lock file _does not_ contain `--indexes` and --find-links` arguments. And so the only way to get those two arguments back in an export is to re-capitulate them on the CLI for Pex to then stuff in the requirements.txt in the proposal above; so that actually doesn't really seem to buy anything.

**Comment by zmanji** [comment]
I think it would be a bit overkill to change the lockfile or have a new export format. I think the current behaviour is fine because either one can pass the same arguments to pip or one can download all of the artifact urls in the lockfile to a directory and pass that as a `--find-links` argument to pip.

This thread can serve as a form of documentation in case anyone runs into this problem.

Thanks for confirming the intended use is to send pip the same resolver arguments as pex got earlier.
