### ISSUE TITLE
Using pex in development?

### ISSUE THREAD

**Issue by ariscn** [pantsbuild/pex#249]
Is pex meant to be used for development, or only deployment? I've had a lot of success deploying pex artifacts, so I'm now taking a hard look at whether it renders local virtualenvs obsolete.

It looks like the following does the trick:

    $ pex -v -r requirements/dev.txt -c ipython -o dist/dev.pex
    $ PYTHONPATH=~/code/project ~/code/project/dist/dev.pex    # absolute path so this works regardless of current directory
    In [1]: import project.stuff

It would be great to see a docs section about development. Is this the Right Way (tm) to use pex in a development workflow? If so, call it out explicitly. If instead there are caveats, or if only the deployment use case is supported / recommended, this should also be explicit.

**Comment by lenucksi** [comment]
Probably an integration with Pantsbuild and the Intellij-Pantsbuild-Plugin would be appropriate at this point. And I would very much welcome your suggestion.

**Comment by kwlzn** [comment]
> "Is pex meant to be used for development, or only deployment?"

in general, I'd like to think we're pretty agnostic on the "purpose" of pex. afaict there's no canonical workflow that pex is better suited for - it's just a tool and library that you can compose into your development, deployment or other such process.

for the most part in practice tho, we (at Twitter) use `pex` as a library via `pants` for development - but that's largely because all of our other development work uses `pants` as well and this helps us do things like share thrift libraries etc between jvm/python apps. how to use pants w/ pex in your development process is already covered in the pants docs (starting here: http://pantsbuild.github.io/python_readme.html and scattered throughout). all of the python related functionality in pants (`python_binary`, `python_library` + the `binary`, `test` goals and so on) utilize pex under the hood via its API. to that end, the cmd workflow you described essentially mirrors how pants' uses pex at a high level, except without the explicit PYTHONPATH manipulation and with pants-based caching/fingerprinting.

I personally tend to use `pex(1)` quite a bit in addition to `pants` for general purpose "development" use - trying out libraries/tools (and at specific target versions) without letting them mutate my installation environment, testing resolves, debugging, etc. I haven't had to (explicitly) create a virtualenv in years and I'm pretty happy about that.

so with that said, I'm not sure this sort of guidance is something pex in general is opinionated enough about to formally document.
