### ISSUE TITLE
py3.5 install issue

### ISSUE THREAD

**Issue by aolko** [pantsbuild/pex#300]
got a pip issues on conda, py3.5, win10x64

```
>pip install pex
Collecting pex
  Downloading pex-1.1.14-py2.py3-none-any.whl (105kB)
    100% |################################| 112kB 578kB/s
Collecting setuptools<20.11,>=2.2 (from pex)
  Downloading setuptools-20.10.1-py2.py3-none-any.whl (509kB)
    100% |################################| 512kB 967kB/s
Installing collected packages: setuptools, pex
  Found existing installation: setuptools 27.2.0
Cannot remove entries from nonexistent file c:\miniconda3\envs\conda-rubito\lib\site-packages\easy-install.pth
```

(yay issue #300(now recursive...kinda))

**Comment by kwlzn** [comment]
this looks like a pip issue rather than a pex issue. it appears to be deinstalling your existing `setuptools` in favor of a lower version required by pex. the latest version of pex should be more permissive in its requirement range for setuptools, which I believe will inherently solve this problem for you.
