### ISSUE TITLE
add option for compiling and striping .py files

### ISSUE THREAD

**Issue by betabrain** [pantsbuild/pex#305]
I noticed the `.bootstrap/` directory in a pex archive contains both the `.py` and the `.pyc` files, which is unnecessary. Anyway, that got me thinking...

It would be nice to have an option, e.g. `--no-source`, which would ensure that only compiled bytecode files end up in the pex archive. Bytecode files are smaller and compress quite well, which would lead to smaller archives and faster deploys.

Any thoughts?

**Comment by kwlzn** [comment]
in general, a `.pyc`-only pex could present limitations in terms of python interpreter compatibility since `.pyc` files encode the compile-time magic number and check against their runtime interpreters magic number. this would prevent e.g. an otherwise python2+3 compatible pex from executing against both interpreters.

however, for controlled use in an environment where this isn't a concern, seems completely reasonable to have this capability behind a feature flag.

if you're in a position to contribute, a PR would be welcome.

**Comment by betabrain** [comment]
Could try. I'm new to the pex source though. From what I get I'd have to change the following parts:

1. `pex/bin/pex.py`: Add command line option
2. `pex/pex_builder.PEXBuilder.build`: Ensure sources are compiled before passing flag to common.Chroot
3. `pex/common.Chroot.zip`: Skip *.py when writing the `zipfile.ZipFile`

Open Questions:
- I'm not quite sure what *freezing* the PEXBuilder does. Is it relevant?

Is that about right?

**Comment by sixninetynine** [comment]
> however, for controlled use in an environment where this isn't a concern, seems completely reasonable to have this capability behind a feature flag.

as neat as this would be - i'm not sure I agree here, since it would be a compile-time feature flag, so the resulting pex would _look_ normal, but potentially misbehave unexpectedly

**Comment by betabrain** [comment]
Most of the time the interpreter will be _specified_ in the shebang, at least in pex generated with default arguments. I get your point though. There is no safety in assumptions.

I guess I will just write a `leanify-pex` script if the need becomes pressing.
