### ISSUE TITLE
inconsistency for opencv-python repl

### ISSUE THREAD

**Issue by wisechengyi** [pantsbuild/pex#325]
with pip install:
```
(venv) $ python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__file__
'/Users/yic/workspace/uArmCreatorStudio/venv/lib/python3.5/site-packages/cv2/cv2.cpython-35m-darwin.so'
```
whereas pex chroot does not have the same directory structure
```
(venv)[tw-mbp-yic uArmCreatorStudio (pants)]$ ./pants repl 3rdparty/python:opencv-python
15:25:45 00:00 [main]
               (To run a reporting server: ./pants server)
15:25:45 00:00   [setup]
15:25:45 00:00     [parse]
               Executing tasks in goals: repl
15:25:45 00:00   [repl]
15:25:45 00:00     [py]
15:25:45 00:00       [repl]

Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import cv2
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: No module named 'cv2'
```
because `cv2` does not directly live under the wheel but `<path to wheel>/opencv_python-3.1.0.3.data/purelib/cv2` hence creating the inconsistency.

Could it be a pex resolve related issue?

Thanks,
Yi

**Comment by kwlzn** [comment]
not a resolve issue, but it does appear that the installation of that wheel fails to land as expected by the package in pex vs how pip handles it.

the wheel is laid out as follows:

```
  Length      Date    Time    Name
---------  ---------- -----   ----
      203  09-28-2016 14:45   opencv_python-3.1.0.3.data/purelib/cv2/__init__.py
 84277784  09-28-2016 15:04   opencv_python-3.1.0.3.data/purelib/cv2/cv2.so
     4784  09-28-2016 15:08   opencv_python-3.1.0.3.dist-info/DESCRIPTION.rst
     5868  09-28-2016 15:08   opencv_python-3.1.0.3.dist-info/METADATA
     1153  09-28-2016 15:08   opencv_python-3.1.0.3.dist-info/metadata.json
      756  09-28-2016 15:08   opencv_python-3.1.0.3.dist-info/RECORD
        4  09-28-2016 15:07   opencv_python-3.1.0.3.dist-info/top_level.txt
      252  09-28-2016 15:08   opencv_python-3.1.0.3.dist-info/WHEEL
```

and this is the form in which it's placed on sys.path by pex.

and a pip uninstall reveals that with no other apparent mechanism, the contents of `opencv_python-3.1.0.3.data/purelib` are moved into `site-packages` during installation:

```
Uninstalling opencv-python-3.1.0.3:
  /Users/kwilson/Python/CPython-2.7.11/lib/python2.7/site-packages/cv2/__init__.py
  /Users/kwilson/Python/CPython-2.7.11/lib/python2.7/site-packages/cv2/__init__.pyc
  /Users/kwilson/Python/CPython-2.7.11/lib/python2.7/site-packages/cv2/cv2.so
  /Users/kwilson/Python/CPython-2.7.11/lib/python2.7/site-packages/opencv_python-3.1.0.3.dist-info/DESCRIPTION.rst
  /Users/kwilson/Python/CPython-2.7.11/lib/python2.7/site-packages/opencv_python-3.1.0.3.dist-info/INSTALLER
  /Users/kwilson/Python/CPython-2.7.11/lib/python2.7/site-packages/opencv_python-3.1.0.3.dist-info/METADATA
  /Users/kwilson/Python/CPython-2.7.11/lib/python2.7/site-packages/opencv_python-3.1.0.3.dist-info/RECORD
  /Users/kwilson/Python/CPython-2.7.11/lib/python2.7/site-packages/opencv_python-3.1.0.3.dist-info/WHEEL
  /Users/kwilson/Python/CPython-2.7.11/lib/python2.7/site-packages/opencv_python-3.1.0.3.dist-info/metadata.json
  /Users/kwilson/Python/CPython-2.7.11/lib/python2.7/site-packages/opencv_python-3.1.0.3.dist-info/top_level.txt
```

and the wheel spec does indicates that this is how a wheel should be "installed": https://www.python.org/dev/peps/pep-0427/#installing-a-wheel-distribution-1-0-py32-none-any-whl

but in pex there's no apparent "purelib" or "platlib" (nee "site-packages") dir afaik.

**Comment by wisechengyi** [comment]
On a second thought, this may not be a pex issue. On pypi https://pypi.python.org/pypi/opencv-python/3.1.0.3, their builds are failing on linux/osx with the same error.

**Comment by kwlzn** [comment]
@wisechengyi that looks like a separate issue importing the cv2.so directly - but it does pickup the `site-packages/cv2` path and in the pex case it does not:

```
Traceback (most recent call last):
  File "/Users/travis/build/skvark/opencv-python/tests/test.py", line 9, in test_import
    import cv2
  File "/Users/travis/build/skvark/opencv-python/venv/lib/python3.5/site-packages/cv2/__init__.py", line 7, in <module>
    from . import cv2
ImportError: cannot import name 'cv2'
```

**Comment by jsirois** [comment]
Played with the wheel api a bit - here the venv contains `wheel==0.29.0`:
```
$ python
Python 2.7.12 (default, Jun 28 2016, 05:44:45) 
[GCC 6.1.1 20160602] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from wheel.install import WheelFile
>>> wf = WheelFile('/tmp/wheel/opencv_python-3.2.0.6-cp27-cp27mu-manylinux1_x86_64.whl')        
>>> wf.install_paths
{'purelib': '/home/jsirois/.pyenv/versions/wheel/lib/python2.7/site-packages', 'headers': '/home/jsirois/.pyenv/versions/wheel/include/site/python2.7/opencv_python', 'scripts': '/home/jsirois/.pyenv/versions/wheel/bin', 'data': '/home/jsirois/.pyenv/versions/wheel', 'platlib': '/home/jsirois/.pyenv/versions/wheel/lib/python2.7/site-packages'}
>>> wf.install(overrides=dict(purelib='/tmp/test', platlib='/tmp/test'))
>>> 
(wheel) jsirois@gill ~ $ ls -l /tmp/test/
total 0
drwxr-xr-x 2 jsirois jsirois  80 Jan 23 11:08 cv2
drwxr-xr-x 2 jsirois jsirois 160 Jan 23 11:08 opencv_python-3.2.0.6.dist-info
(wheel) jsirois@gill ~ $ ls -l /tmp/test/cv2/
total 17880
-rwxr-xr-x 1 jsirois jsirois 18303475 Jan 23 11:08 cv2.so
-rw-r--r-- 1 jsirois jsirois      203 Jan 23 11:08 __init__.py
```

So by overriding install paths (I ignored 3 of the 5 here, but they would be important too), the WheelFile API could maybe directly be used to help pex distill wheels directly into its own chroots.

**Comment by mgrandi** [comment]
This seems to be happening to me with SQLAlchemy as well, except it seems to be intermittent? I have a few PEX files that have SQLAlchemy in the `.deps/sqlalchemy.whl/sqlalchemy.data/purelib/sqlalchemy`folder, and other ones where it is fine (just `.deps/sqlalchemy.whl/sqlalchemy`

when sqlalchemy is in the `purelib` folder, and I try to run the PEX, it fails saying it can't find the module.

**Comment by MarkChuCarroll** [comment]
I'm encountering this issue with both opencv, and with tensorflow, which uses the same layout structure. Before I put in a bunch of time figuring out the pants/pex internals to fix it, is anyone actively looking at this issue?

**Comment by kwlzn** [comment]
@MarkChuCarroll don't believe anyone is actively looking into this. the fix here will essentially be to "install" wheels into the pex vs just unzipping them. John demo'd the exact API that should be used - and a PR for that with solid test coverage would be welcome.

**Comment by MarkChuCarroll** [comment]
@jsirois Do you mean the WheelInstaller API? That's where it looks like this belongs to me, and I can't find a WheelFile API in pex.

**Comment by MarkChuCarroll** [comment]
@jsirois @kwlzn I'm struggling with the fix to this - I've found a couple of alternative ways to solve it, none of which I'm really happy with.

The problem, as I understand it:

A simple wheel is just a zip file containing a set of files and directories which include the package source. When those are installed  by pip, depending on the setting of the setting of the Root_Is_Purelib
parameter of the WHEEL metadata, it's installed into either the purelib or platlib directory. Inside of a PEX, we can just unzip one of these directories, and arrange, during the PEX bootstrap, for that directory to get added to the sys.path. (because, once it's in a pex, the distinction between purelib and platlib isn't relevant - whether the root is purelib or platlib, it needs to get added to the
PYTHONPATH.)

Wheels, however, don't always follow this simple structure. When they want to specify stuff to be installed in multiple places (eg, some code in purelib, some in platlib; or some purelib and some headers; etc.), they can include a package.data directory. That contains subdirectories, whose name is the install path element that their contents should be put into. 

For example, we have opencv, which contains a set of data files and a set of purelib source files. So opencv_python-3.2.0.7-cp27-cp27mu-linux_x86_64.whl contains opencv_python-3.2.0.7-cp27-cp27mu-linux_x86_64.data, which has two subdirectories - data (containing some text files) and purelib (containing the actual python modules).

In a wheel with a data thing, the pex trick of just adding the wheel root to the sys.path doesn't work. For example, in opencv, we'd end up adding the wheel location .deps/opencv_python-3.2.0.7-cp27-cp27mu-linux_x86_64 to the sys.path, but the python modules are actually in .deps/opencv_python-...-x86_64.data/purelib.  

In fact, we really need to get the contents of all of the .data directory subdirectories into a place where the python interpreter needs to load them. Fortunately, in the pex world, we don't really need to maintain the distinction between the different instal_path components - they're all just things that need to wind up on the sys.path for loading.

John's initial comment suggested that they way to handle this is to take advantage of the fact
that a wheel knows how to install itself: we can create a WheelFile, and use it's install
method, with the target locations for the different install path elements overridden appropriately
for a pex. 

If I'm understanding John's suggestion correctly, to make this work, we'd need to create new directories in the pex corresponding to the install_path components, and then tell the wheel  to install itself into those directories. (Basically, we'd be creating something that looks like sitelibs into a pex - instead of .deps/opencv...whl/ containing the contents of opencv, we'd have a .deps/sitelibs, which contains all of the python module sources for things in the pex.)  This is the cleanest solution, in terms of using wheels the way they're intended, but it would be a pretty substantial change to the internal structure of a pex.

Alternatively, we can leave the pexes as is, and change the way that the pex bootstrap computes
the sys.path when it runs a pex, so that if a wheel contains a .data dir, we add
each of its components to the sys.path. This feels much uglier, but it wouldn't perturb the way that pexes currently operate.

I've got a working prototype of the latter approach, for which I'm
working on tests. But before I spend too much more time banging away at it, I'd
like to verify that (a) the stuff I figured out above is correct, and (2) the
sys.path modification approach is something that is acceptable to the PEX maintainers.

**Comment by MarkChuCarroll** [comment]
As I go deeper and deeper down this rathole, I'm losing hope that this can be done in a reasonable way. The guts of pex repeatedly make pretty strong assumptions that a distribution contains a single source tree in the root of  the distribution archive. That's simply not true. But the assumption goes deep. Wheel files are getting piggybacked into the egg finders, which are built on the assumption that eggs follow the eggs spec, which says that eggs have a structure that allows them to be included in sys.path.

**Comment by kwlzn** [comment]
(apologies for the delayed response, have been out on vacation for the past two weeks)

yeah. to mirror `pip` et al, it'd be ideal if the pex could install all distributions into something resembling a shared `site-packages`-like dir within the pex. as you mention tho, this is likely to break several key assumptions within pex around things like runtime platform resolve checking, etc which depend on the pex containing all requisite "resolvables" rather than their "installations".

furthermore, I think you'd also need multi-universe permutations of this shared `site-packages`-like dir for all combinations of runtime interpreter version, platform/abi, etc - or you could tease out universal vs platform-specific dirs and then compose them via `sys.path` (but that might also break some packaging assumptions that expect shared composability). at any rate, keeping both the full contents of the `.whl` file itself *and* its "installed" representation with permutations is likely to bloat the size of produced pex files.

one possible solution here might be to simply treat any whl-bound deps as a variant of not-zip-safe and then construct, cache and use a shared `site-packages`-like dir at runtime in the `PEX_ROOT` path (e.g. `~/.pex/wheel_install/<fingerprint>/*`). assuming a wheel-specific impl, I think this should be pretty reliable and quick enough to do at runtime - particularly if cached.
