### ISSUE TITLE
Passing Arguments

### ISSUE THREAD

**Issue by trivigy** [pantsbuild/pex#326]
Anyway when building a pex file to specify, along with the entry-point, some arguments that will be passing during execution? Sort of like binding preset arguments to the entry-point during the build process?

**Comment by kwlzn** [comment]
not currently. most of the time we solve this with either wrapper scripts or by simply creating a custom entrypoint which calls the original entrypoint with default args and can do things like override/merge arguments.

with pex as the holder of bound preset args, merging runtime args with default values wouldn't be generally feasible which feels like a limitation. also, since the PEX entrypoint can change at runtime it's unclear how prebound args would be handled in that case. 

what's your use case?

**Comment by trivigy** [comment]
I am wrapping pex with a bazel build rule. The specific use case is that I am generating a dependency tree using bazel and then pipe all the bash paths of the individual python packages into a command line pex script that outputs a final built executable file. Right now I am trying to add a tester to that logic and the way I did it was by creating a custom tester package that goes through the sys.path() inside of the pex env (after build) and imports all of the relevant tests/ folders and the associated tests into the tester for execution. Sort of building a fully encompassing test suite while relying on the bazel dependency tree. In order for me not to have to compute on the fly a script I was hoping I could just add the args in command line to point to the actual packages. (to distinguish between my dependencies vs system and external dependencies.)

When pex builds the packages (ones that are local) and installs them, how does the name of the folders is computed? it seems like it follows whatever is the package name however, if my package is called "blah-blah" the folder name ends up being 'blah_blah_0.1..."

Anywhere I could look up the actual command?

**Comment by kwlzn** [comment]
> When pex builds the packages (ones that are local) and installs them, how does the name of the folders is computed? it seems like it follows whatever is the package name however, if my package is called "blah-blah" the folder name ends up being 'blah_blah_0.1..."

it's the equivalent of `python setup.py bdist_wheel` etc against the original package's sdist. for wheels, it's standard convention to convert `-` in the package name to `_` when writing the wheel filename.

**Comment by trivigy** [comment]
@kwlzn ahhhhhh.... Thanks a lot. One last question. Here are two examples:
```
protobuf-3.1.0.post1-py2.py3-none-any.whl
multidict-2.1.4-cp35-cp35m-linux_x86_64.whl
```
one says none-any and another says linux_x86_64. What dictates the version?

**Comment by kwlzn** [comment]
see the specs here:
  - https://www.python.org/dev/peps/pep-0491/#file-name-convention
  - https://www.python.org/dev/peps/pep-0425/#overview

the first field is the 'abi type' - `none` in the protobuf example and `cp35m` in the multidict. `none` indicates that it need not conform to an abi type because it's pure python code. `cp35m` indicates compatibility with CPython 3.5.x with pymalloc (m) and short (ucs2) unicode support.

the second field is the 'platform type' - `any` in the protobuf example indicates a "universal" wheel - or one that is pure python and can be executed by any python interpreter. `linux_x86_64` is the normalized name for `linux-x86_64`, which indicates this wheel carries platform-specific code (e.g. C extensions) that have been compiled specifically for linux-x86_64.

**Comment by trivigy** [comment]
This is very helpful. Thank you a lot. I would say that this issue is resolved then, unless you would want to mark this as a feature request.
