### ISSUE TITLE
pex does not use .pip/pip.conf to resolve packages

### ISSUE THREAD

**Issue by salimfadhley** [pantsbuild/pex#336]
I'm able to install some packages with Pip like this:

`(venv) [me@myhost glances]$ pip install -r requirements_glances.txt`

However when I attempt an equivalent syntax with Pex I get the following:

```
(venv) [me@myhost glances]$ pex -r requirements_glances.txt -o glances.pex
Could not satisfy all requirements for glances:
    glances
```

It looks like Pex doesn't honor my site config (in ~/.pip/pip.conf) - is there any way to explicitly change the index that Pex uses when resolving requirements?

**Comment by kwlzn** [comment]
```
$ pex -h |grep -A12 "Resolver options"
  Resolver options:
    Tailor how to find, resolve and translate the packages that get put
    into the PEX environment.

    --pypi, --no-pypi, --no-index
                        Whether to use pypi to resolve dependencies; Default:
                        use pypi
    -f PATH/URL, --find-links=PATH/URL, --repo=PATH/URL
                        Additional repository path (directory or URL) to look
                        for requirements.
    -i URL, --index=URL, --index-url=URL
                        Additional cheeseshop indices to use to satisfy
                        requirements.
```

so, `pex -r requirements_glances.txt --no-pypi -i http://your-custom-index -o glances.pex`

**Comment by salimfadhley** [comment]
One issue: The private repository is password protected, do you know if there's a way to provide some authentication information?

`pex -r requirements_glances.txt --no-pypi -i http://<user>:<password>@<server>:8081/artifactory/api/pypi/virtual-pypi/simple -o glances.pex
`
This gives the exact same "could not satisfy all requirements" error.

Also is there a way to debug what HTTP requests Pex is actually making? 

I suppose the work-around is just to pre-fetch all the requirements before running Pex, but I'd rather build everything directly from Artifactory if I can.

**Comment by sixninetynine** [comment]
@salimfadhley I believe that pre-fetching and then using `--no-pypi` is _currently_ your best bet when not using pypi directly. 

@kwlzn I recall there being an issue or PR suggesting tighter integration with `pip` (or at least the underlying libraries powering `pip`). Seems like a lot of the issues in the tracker are regarding compatibility with pip. What are your thoughts on reworking some of the package resolution stuff? Could be useful for folks that work with `conda` as well.

**Comment by salimfadhley** [comment]
Something still seems to be wrong:

```
(venv) [user@server glances]$ ls ./wheelhouse/
bottle-0.12.11-py2.py3-none-any.whl
enum_compat-0.0.2-py3-none-any.whl
Glances-2.7.1-py3-none-any.whl
netifaces-0.10.5-cp35-cp35m-linux_x86_64.whl
psutil-5.0.1-cp35-cp35m-linux_x86_64.whl
pystache-0.5.4-py3-none-any.whl
scandir-1.4-cp35-cp35m-linux_x86_64.whl
six-1.10.0-py2.py3-none-any.whl
statsd-3.2.1-py2.py3-none-any.whl
zeroconf-0.17.6-py2.py3-none-any.whl
```

But I'm still getting the bad-interpreter message:

(venv) [user@server glances]$ pex -o glances.pex --no-pypi --find-links=./wheelhouse/  -r ./glances_requirements.txt -m glances --python=/efs/dist/python/core/3.5.1/exec/bin/python3 -vvvv
pex: Building pex :: Resolving interpreter :: Setting up interpreter /efs/dist/ppex: Constructed RequestsContext context <pex.http.RequestsContext object at 0x7f4de74a9c88>
pex: crawling link i=0 link=Link('file:///usr_data/tmp/glances/wheelhouse') follow_links=False
pex: Building pex :: Resolving interpreter :: Setting up interpreter /efs/dist/python/core/3.5.1-build002/.exec/x86-64.rhel.6/bin/python3.5 :: Interpreter cacheCould not find compatible interpreter
(venv) [user@server glances]$

[This ticket](https://github.com/pantsbuild/pex/issues/232) suggests that there's a limitation that some of the dependencies have to be regular source-distributions and not wheels, however there's nothing in the output above that would indicate this is the nature of the fault.

**Comment by iksaif** [comment]
Would be great to have both pip.conf and https://github.com/pypa/pipfile support.

**Comment by saimeCS** [comment]
I'm in a similar situation.
I'm using pex in a CI workflow with no direct access to Pypi. We have to use a corporate Nexus repository that is accessible in https with a certificate.
Everything works fine with pip which uses a pip.conf file with the path to the certificate.
How can I tell pex to use this certificate ?

**Comment by Gerardwx** [comment]
Pex would be more useful if it also parsed .[pypirc ](https://packaging.python.org/specifications/pypirc/)files. As others have mentioned, some of use private repositories that require a password, so the -f or -i switches don't seem to work.

**Comment by jsirois** [comment]
Ok, @Gerardwx's comment woke this old issue up for me. Pex currently explicitly turns off pip.conf via `pip --isolated` since Pex needs to configure certain switches to certain values for correct operation. It may be that Pex could allow pip.conf if it is the case that Pex could still call Pip and override any of the values set there it needs to have a certain way (these are mainly all `pip download` options).
___
@saimeCS
> I'm in a similar situation.
I'm using pex in a CI workflow with no direct access to Pypi. We have to use a corporate Nexus repository that is accessible in https with a certificate.
Everything works fine with pip which uses a pip.conf file with the path to the certificate.
How can I tell pex to use this certificate ?

Modern Pex supports all relevant Pip options here including --proxy, --cert and --client-cert.
___
@Gerardwx 
> Pex would be more useful if it also parsed .pypirc files. As others have mentioned, some of use private repositories that require a password, so the -f or -i switches don't seem to work.

Presumably you can get things working with Pip? If so that same setup should work with Pex except for using pip.conf which we currently turn off purposefully via `pip --isolated`.

**Comment by goddtriffin** [comment]
For those blocked on this: one workaround I've found is that you can specify multiple `--index-url`s on a single `pex` command to specify multiple PyPi URLs. This is contrary to the way `pip` handles this; you _cannot_ use `--extra-index-url` on a `pex` command.

**Comment by jsirois** [comment]
You can also pass Pex `-r requirements.txt`. you can pass global flags to Pip via that file as well. See: https://pip.pypa.io/en/stable/reference/requirements-file-format/#global-options

**Comment by jsirois** [comment]
I just looked into this and the pip configuration consultation order looks like it makes disabling `--isolated` safe: https://pip.pypa.io/en/stable/topics/configuration/#precedence-override-order

**Comment by jsirois** [comment]
@iksaif I just noticed your comment about Pipfile support. Pex has since grown its own more comprehensive support for generating and consuming lockfiles in addition to having PEX files turn themselves into venvs, etc. For locking you might check out `pex --help` for `--lock` and `pex3 lock --help`. For venvs you can look at `pex --help` for `--venv*` and `pex3 venv --help` as well as `PEX_TOOLS=1 the.pex venv --help` for a PEX file built with `--include-tools` (or `--venv`).

So still no support for reading Pipfile, but support for what it does as a potential replacement.
