### ISSUE TITLE
Improve pex resolver caching for local dist resolves

### ISSUE THREAD

**Issue by CMLivingston** [pantsbuild/pex#452]
This is an upstream issue from: https://github.com/pantsbuild/pants/issues/5449

Currently, the pex resolver handles resolving dists and caches them using the name of the wheel in the pex resolver cache. This can be problematic if two locally-built (and locally resolved via a find-links fetcher), setup.py-based Python projects have the same name and version info in their respective setup.py's. This could lead to undefined behavior in the event that there is a collision in the pex resolver cache.

The scope of this ticket is to improve the pex resolver caching logic for the use case where dists are resolved from local fetcher directories, allowing for the resolution of uncached dists in the event that two dists have the same name and version but have different contents. This solution should be generalizable to any case where the cached dist contents differ from an equally versioned dist with the same name.

**Comment by jsirois** [comment]
> This can be problematic if two locally-built (and locally resolved via a find-links fetcher), setup.py-based Python projects have the same name and version info in their respective setup.py's.

The upstream issue seems most sanely solved by never mutating a published version. IE, (pseudocode) use `python setup.py egg_info --tag-build $(target.transitive_invalidation_hash()) sdist` (for example) to always publish a unique version.

If that works for upstream (downstream?) is there any further motiviation for this feature?

**Comment by cosmicexplorer** [comment]
The analogy to jvm `-SNAPSHOT` deps you made in [your other comment](https://github.com/pantsbuild/pex/pull/520#issuecomment-402815847) seems really reasonable to me. I don't know if there is need specifically for this, personally -- when I first started looking at this I was convinced it was necessary for pantsbuild/pants#6022, but since we're just using `--tag-build` as you describe in that PR I think this issue can be resolved in pants alone (or at least, the integration test in that PR which tests invalidation passes). I will probably close #453 after spending some more time getting the pants PR I mentioned to pass CI.

**Comment by CMLivingston** [comment]
This makes sense to me, no further motivation. Closing this issue.
