### ISSUE TITLE
Can we make pex read from a requirements.txt file instead of specifying each requirement separately?

### ISSUE THREAD

**Issue by legalosLOTR** [pantsbuild/pex#5]

**Comment by cdgraff** [comment]
+1

**Comment by areitz** [comment]
I believe that if you are using pants to make your PEX file, this is already supported:

http://pantsbuild.github.io/3rdparty_py.html#3rdpartypython

**Comment by wickman** [comment]
Totally agree that we need this feature.  @areitz: It's nice that pants makes an effort with requirements.txt but it's a super heavyweight tool for most people and also it doesn't even really support the spec: https://pip.pypa.io/en/latest/reference/pip_install.html#requirements-file-format

I started working on this about a year ago and pushed a preview branch a few months ago here:
https://github.com/wickman/pex/blob/wickman/requirements_txt/pex/requirements.py

The challenge is that requirements.txt is pretty pip-specific, even letting pip command line flags creep into the specification.  It's also just poorly designed and does not compose particularly well (e.g. with nested requirements.txt files.)  It's also constantly changing, as both pip and setuptools have undergone significant change over the last year.  Writing greenfield code to support the abstractions of requirements.txt in a sensible way has been difficult mostly because it's just not a very sensible spec.

It's my intention that pex 1.0 will support requirements.txt and change the pex command line flags to resemble pip's more closely (e.g. instead of pex -r req1 -r req2, it will be pex -r requirements.txt req1 req2) but it's probably a month away before I can devote the time to finish this up.

**Comment by spinus** [comment]
+1

**Comment by sholsapp** [comment]
+1 :)

**Comment by wickman** [comment]
Latest commit at https://github.com/wickman/pex/tree/wickman/requirements_txt with all tests passing.  Only thing missing is the installation of directory-based resolvables (e.g. 'pex .' a la 'pip install .')  I plan to work on that next.

I'm going to start a 1.0.0-dev0 branch on pantsbuild/pex and start applying backwards compatible changes there.  Once wickman/requirements_txt goes through review, I'll apply it to 1.0.0-dev0.  I will try to sprint through most of the incompatibilities outlined in #60 and mint 1.0 by the end of PyCon.  If anyone is at PyCon, feel free to join me at the packaging sprint to work through these patches.  Thanks!

**Comment by sholsapp** [comment]
I'll stop by!

**Comment by wickman** [comment]
Fixed at 8b7bb05c.  You can use this by building a copy with 'tox -e py27-package' from master.  I will publish 1.0.0.dev0 soon but will require pip --pre to install via pip.

**Comment by esazhin** [comment]
awesome! thanks a lot!
