### ISSUE TITLE
pex --python seems to ignore the selected interpreter path

### ISSUE THREAD

**Issue by warsaw** [pantsbuild/pex#53]
```
% ls -l /usr/bin/python3
lrwxrwxrwx 1 root root 9 Dec  1 00:12 /usr/bin/python3 -> python3.4*
% pex -v --python=/usr/bin/python3 -o world.pex -r world --no-wheel -e worldlib.__main__:main
pex: Resolving distributions: 517.2ms          
pex:     Packaging world: 354.3ms
  world 3.1
Setting entry point to worldlib.__main__:main
Saving PEX file to world.pex
% head -1 world.pex
#!/usr/bin/env python3.4
```

It doesn't seem to matter if ```--python=/usr/bin/python3.4``` is used (i.e. it's not related to python3 being a symlink).

**Comment by wickman** [comment]
Yeah, hard to tell if this is a feature or a bug.  The way pex treats interpreters is as "interpreter classes" -- a tuple of flavor (CPython, PyPy) and major/minor version (2.6, 2.7, 3.4.)  So when you do --python=<explicit path> it uses that interpreter to build dependencies but then synthesizes the shebang line based upon the interpreter class instead of as the explicit interpreter.  This is mostly for pex portability sake, since '#!/home/wickman/herp/derp/python2.7" is usually not what you want (but admittedly, it could be useful.)

Right now PEX_INTERPRETER is just a boolean to determine whether or not to drop into a repl.  I'd like to change that to PEX_REPL=1 and use PEX_INTERPRETER the same way as --python.  In other words, if it's an explicit path, re-exec to that interpreter, otherwise, try and search $PATH for an interpreter that satisfies a requirement e.g. PEX_INTERPRETER='PyPy>=2.4,<2.5'.  This is why the PythonInterpreter.replace method exists but it has not yet been used in practice.

**Comment by warsaw** [comment]
Just to provide a use-case: I'm building a pex that will then get further bundled into a distributable format for Ubuntu Core Snappy.  In that execution environment, there may not be a suitable $PATH to resolve the shebang, but I know that /usr/bin/python3 (or /usr/bin/python3.4) will exist.  So I need a way to tell pex "no, really, this is the exact path I want you to use for the shebang".  It's tricky to munge the shebang after the pex has been written.

**Comment by wickman** [comment]
Totally agree this makes sense.  I don't want it to be the default behavior but we should allow this.  It should probably be an option to PythonInterpreter (e.g. preserve_hashbang=True?) but not completely sure what the API should look like.  Thoughts?

**Comment by warsaw** [comment]
Looking at just the --help output, I found it surprising that --python *didn't* preserve my argument verbatim.  I'm not sure if you've been following PEP 441, but we had a similar discussion over there.  Totally get the need for pex to preserve its backward compatibility of course.  I suppose in that case, something like ```--shebang=<everything-after-hashbang-exactly-preserved>``` would make sense.  Maybe that would have to be mutually exclusive with --python?

**Comment by wickman** [comment]
Good point.  I thought about it a little more and I thought you're right, --python should probably be 'use this interpreter, exactly.'  Perhaps a separate command flag, --python-version, could be switched out with the current --python semantics.

**Comment by warsaw** [comment]
On Feb 20, 2015, at 02:39 PM, brian wickman wrote:

>Good point.  I thought about it a little more and I thought you're right,
>--python should probably be 'use this interpreter, exactly.'  Perhaps a
>separate command flag, --python-version, could be switched out with the
>current --python semantics.

+1 :)

**Comment by wickman** [comment]
I ultimately decided to leave --python alone.  However, I added --python-shebang which allows you to set the shebang line exactly.

I also added the PEX_PYTHON environment variable which allows you to change which interpreter invokes the PEX, e.g.

```bash
mba=pex=; head -1 dist/pex
#!/usr/bin/env python2.7

mba=pex=; PEX_PYTHON=pypy PEX_INTERPRETER=1 dist/pex
Python 2.7.8 (f5dcc2477b97, Sep 19 2014, 18:09:54)
[PyPy 2.4.0 with GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> 
```

This is on master now with 1.0.0.dev3.  'tox -e py34-package' to build a pex with all the above functionality.
