### ISSUE TITLE
Is there a canonical way to run a script inside a dependency?

### ISSUE THREAD

**Issue by AlexHill** [pantsbuild/pex#626]
My program depends on awscli, and I'd like to include it in my pex bundle instead of relying on it being present in the system.

If i'm running in a normal virtualenv, I can look at `sys.executable` and call `aws` in the same directory. But if I'm running in a pex, `sys.executable` just points to the system Python, so that doesn't work.

What does work perfectly is running my pex with `PEX_SCRIPT=aws`, so I'm wondering if there's a canonical way to either do this, or to get any pex context information at runtime, like whether or not we're running from a pex or the path to the pex bundle?

**Comment by jsirois** [comment]
The `PEX_SCRIPT` technique is approximately equivalent to this technique which you could be using in your virtualenvs:
```
python -c "import pkg_resources; next(pkg_resources.iter_entry_points('console_scripts', 'pytest')).load()()" --help
```
This runs `pytest --help` in a virtualenv that has pytest installed (and setuptools).

If you have multiple entrypoints in your pex and you want to shell out to one, you can use `sys.argv[0]` as your interpreter - that's the pex itself. For example:
```
$ rm -rf /tmp/my_app && mkdir /tmp/my_app && cat << EOF > /tmp/my_app/my_app.py
import subprocess
import sys
subprocess.check_call(sys.argv, env={'PEX_SCRIPT': 'pytest'})
print('TADA!')
EOF
$ pex -D /tmp/my_app pytest -e my_app -o my_app.pex
$ ./my_app.pex --version
This is pytest version 4.0.0, imported from /home/jsirois/.pex/install/pytest-4.0.0-py2.py3-none-any.whl.9f103621b5f9de64560c6e42fec956dd9a5d200e/pytest-4.0.0-py2.py3-none-any.whl/pytest.py
TADA!
```

**Comment by AlexHill** [comment]
Thanks for the detailed response, that's given me a bit more insight.

the `pkg_resources` approach looked really promising, but `awscli` packages its binaries as `scripts` instead of `entry_points`.

I realised I can import `_pex` when I'm running inside a pex and not otherwise, so my solution for now is to in that case, create a temporary shell script essentially doing `PEX_SCRIPT=aws <sys.argv[0]> "$@"` and add that to `PATH`...

**Comment by jsirois** [comment]
Aha - ok. PEX creates pexes with all embedded wheels with scripts at `.deps/<whl>/bin/<script>`. We could provide an api like `pex.runtime.execute_script('awscli', 'aws', **kwargs)` where kwargs were subprocess.POpen kwargs. As well as a companion context manager `pex.runtime.script_path('awscli', 'aws')` that materialized the script to a tmpdir and yielded the script path. To use this, you'd need to add pex to your python project's explicit install_requires dependencies and internally these functions would need to 1st consult `pex.runtime.pex.runtime.running_from_pex' (see discussion here: https://github.com/pantsbuild/pex/issues/721#issuecomment-495703792) and if not running from within a pex, use your technique or setuptools to find an execute the script; otherwise find the script inside the pex.

Does this API approach seem reasonable?
