### ISSUE TITLE
Is it possible to include conda environment in pex file?

### ISSUE THREAD

**Issue by timtutt** [pantsbuild/pex#627]
I'm running into a fairly irritating issue where I'm able to install a package via `conda install`, but cannot install or collect the wheels via `pip install` or `pip wheel`... I'm using an anaconda virtual env, and everything works locally. I'd like to just package the entire conda virtual env inside of the pex file, but can't seem to find a way to do this...

Is what I'm looking to do possible? Are there alternative solutions?

**Comment by jsirois** [comment]
From what I can tell after a quick install of miniconda3 and then a `conda create -n scipy scipy`, pex is not really close to being able to handle this. The `conda create` and `conda install` commands appear to install custom native libraries. This would make sense, since the target audience consumes a bunch of python libraries that are hard to install / depend on native libs! Currently, pex only deals in python standards: wheels, eggs, sdists and the associated PEPs. It does not handle installing non-python dependencies or now about external tools that can do so.

I don't of any alternative solutions.

I think it would be wonderful if pex or an offshoot / similar tool could create multiplatform pex's that could handle activating pre-packaged out of band native libs. This would be a good deal of work though and, like most OSS projects, we're strictly volunteer at this point, so it seems in the near term a solution that fits your needs would have to come from a motivated contributor.

**Comment by jsirois** [comment]
I'm going to close this as "answered", but I'm happy to exchange ideas in this thread if you have more comments.

**Comment by MannyKayy** [comment]
+1 for this feature
