### ISSUE TITLE
Parse 'Requires-Dist' markers

### ISSUE THREAD

**Issue by zmanji** [pantsbuild/pex#7]
A current bug with pex is that it will resolve dependencies for the packages in the python environment of the `pex` program, not the target python environment of the output pex.

For example if `pex` is running under Python 2.7, it will end up not adding `argparse` to the final pex even if the user specifies a target of Python 2.6.

To remedy this we need to extract the `Requires-Dist` metadata out of every distribution we are going to add. This metadata (described in [PEP 345](http://legacy.python.org/dev/peps/pep-0345/)) contains entries like `argparse; python_version == '2.6'`. If we take this metadata, pass it to the target interpreter, let the target interpreter evaluate the metadata and let the target interpreter decide if we need to add the requirement for the distribution or not.

The easiest way to implement this is to first change the [resolution](https://github.com/zmanji/pex/blob/507c1168c997cd40cf2510ddd3cb1370899c2a53/pex/resolver.py#L204) code to read the `Requires-Dist` metadata and then pass that data to the target interpreter, similar to how we [evaluate the target interpreter version](https://github.com/zmanji/pex/blob/507c1168c997cd40cf2510ddd3cb1370899c2a53/pex/interpreter.py#L235).

**Comment by jsirois** [comment]
This state of affairs is now finally fully buttoned up with enhancements to `PythonInterpreter`: https://github.com/pantsbuild/pex/blob/3e71bc7896935a8177e9bbe9399769c3522528dc/pex/interpreter.py#L278-L286, `AbbreviatedPlatform` (`--platform`): https://github.com/pantsbuild/pex/blob/2b3bdee8cd99ffab0538a63fdd36de8de356f857/pex/targets.py#L214-L238 and the introduction of `CompletePlatform` (`--complete-platform`): https://github.com/pantsbuild/pex/blob/2b3bdee8cd99ffab0538a63fdd36de8de356f857/pex/targets.py#L246-L280

The abbreviated `--platform` case does not have enough information to form a full set of environment markers; so the surrounding code just hard fails iff solving of a resolve requires evaluating the missing env markers; otherwise, it proceeds correctly. This usually works since most env markers in the wild are `python_version` markers, but it fails when it should with the remedy of supplying a `--complete-platform`.
