### ISSUE TITLE
Is it possible to exclude certain transitive dependencies from the PEX?

### ISSUE THREAD

**Issue by erwa** [pantsbuild/pex#737]
I am building a PEX where some dependencies transitively depend on the CPU TensorFlow build and others depend on the GPU TensorFlow build. Both get installed and the latter wins. If the CPU TF build gets installed last, then I can't access GPUs when running my PEX. Is it possible to explicitly exclude a transitive dependency when building a PEX?

**Comment by jsirois** [comment]
It is not.

That said, resolution of requirements during building of a PEX and subsequent activation of those requirements when running a PEX (ie: the `sys.path` order of the requirements) should be stable and respect the rule of nearest 1st. As such, you might try ammending your pex command to:
```
pex [ existing options] tensorflow_gpu [existing requirements]
```

In other words, inject an artificial top-level requirement on `tensorflow_gpu`. This will be compatible with whatever version the underlying lib needs and, since listed 1st, should resolve 1st and be acitvated on the `sys.path` 1st ensuring an import of `tensorflow` always finds it in the `tensorflow_gpu` dist which is forced earliest on the `sys.path` constructed by the PEX runtime.

**Comment by jsirois** [comment]
I'm going to close this as answered but I'm not fully confident of the solution so please report back good or bad, and if bad we can re-open and/or file a feature request issue to explicitly support a blacklist option for requirements.

**Comment by erwa** [comment]
Hi @jsirois, the problem with installing both tensorflow_gpu and tensorflow_cpu is that they have the same package names and one will overwrite the others' files. So it's not a matter of which is on sys.path first, it's which gets installed last.

In any case, I managed to work around the issue by switching to using shiv: https://shiv.readthedocs.io/en/latest/

**Comment by jsirois** [comment]
Gotcha. PEX does not install these packages in the way you might guess though. It includes their extracted wheels inside the pex and then later explodes their contents onto disk in seperate subdirs under `~/.pex/install/[unique dir name per wheel]`.

It looks like shiv doesn't have an exclude option either, but I'm guessing it works for you since it does pip install into a single directory where over-writes are an issue, but you control the order working around the issue.

**Comment by JoshuaCWebDeveloper** [comment]
In my case I was building by passing my requirements.txt and was able to exclude `tensorflow` (the CPU package) using grep, so that only `tensorflow-gpu` would be built (the `=` at the end of the regex is to ensure that only that specific package is matched):
```
pex -m mymodule -r <(pip freeze | egrep -v tensorflow=) -o test/build.pex
```
