### ISSUE TITLE
Interpreter discovery and pyenv don't interact well

### ISSUE THREAD

**Issue by benjyw** [pantsbuild/pex#782]
At pex runtime, interpreter discovery looks on the PATH for any binary with a name that looks like it might be a python interpreter, and executes it to get its version (and verify that it is in fact a python interpreter). 

Unfortunately, pyenv can create a large number of such files in `~/.pyenv/shims`. E.g.,

```
> ls /Users/benjyw/.pyenv/shims/ | grep -E "python\d?(.\d)?m?$"
python
python2
python2.7
python3
python3.5
python3.5m
python3.6
python3.6m
python3.7
python3.7m
>
```
Note that these aren't symlinks, but wrapper scripts, so pex's realpath deduping doesn't help.

So, pex will execute every one of these, plus whatever other python interpreters it finds, which adds up to non trivial overhead (~1 second in the above example) on every run of the pex. Note that not all of these are actually valid python interpreters - some are shim stubs that fail on purpose.

**Comment by benjyw** [comment]
I don't have an obvious solution here. Some heuristics to discuss:
1. Checking the interpreter pex is running under first. It may be likely to be the right one?
2. Stopping as soon as we find a valid interpreter, instead of first executing all of them and then comparing. This won't help in the worst case but probably will the average case.  This will effectively implement 1.
3. An on-disk interpreter cache, in some well-known location, to speed up subsequent runs.  This won't help much in container scenarios.
4. Be smarter about matching names to versions. E.g., if the user specified Python>=3.7, we can eliminate many versions just by naming convention.

**Comment by jsirois** [comment]
It would definitely be good to implement 1 directly, this is already nodded towards in some of the machinations in `maybe_reexec_pex`, but the treatment does not include the cases where PEX_PYTHON or PEX_PYTHON_PATH are set:
https://github.com/pantsbuild/pex/blob/e5317cbc94a49d5129144806ce4117ccd926fb6a/pex/pex_bootstrapper.py#L165-L168
Presumably this catches the majority of cases - the current interpreter is fine.

Instead of 2 a multiprocessing approach could probe all interpreters in parallel. Perhaps too complex.

Item 4 makes sense, but I think 1 and maybe 2 might do it.

**Comment by jsirois** [comment]
I took a whack at point 1 in #783.

**Comment by jsirois** [comment]
#835 released as part of Pex 2.1.0 only made interpreter identification slower per interpreter; so finishing out a few of the other mitigations in this issue has come to the fore. Parallelization is now pretty straightforward given the groundwork in `pex.jobs` so I'll knock that out first and then likely an interpreter cache.

**Comment by jsirois** [comment]
Items 1-3 above are now implemented. Item 4 is problematic and very much less important now that paralellization and caching are in effect.

As a postscript, item 4 turns out to be particularly problematic due to pyenv shims. These, when on the `PATH`, have the behavior of re-directing `python*' to the "correct" python as configured by `pyenv (local|global)`. As such, executing the python3 shim "binary" can land you in a python2 interpreter, defeating any hueristic that does not also special case binaries residing inside the pyenv shims dir.

**Comment by jsirois** [comment]
Improving this even further while solving bugs is https://github.com/pantsbuild/pex/pull/1325. We now handle shims 1st class and skip interpreter identification for inactive ones and then de-dup the remaining active ones by pre-resolving those shims to the versions they point to
