### ISSUE TITLE
Possible code copy / paste error

### ISSUE THREAD

**Issue by huornlmj** [pantsbuild/pex#844]
https://github.com/pantsbuild/pex/blob/a2b6d0a645824e5ed20e422f34482b60e0e7cdd6/pex/vendor/_vendored/setuptools/setuptools/glob.py#L56

The outcomes of the if / else logic in _iglob both "yield pathname".  Should the 'else not "yield dirname" instead?

**Comment by jsirois** [comment]
I'll only comment in depth here since #845, #846, #847 and #848 are all similar, but all the problems you point out are in vendored code. This is code not owned by pex, but installed read-only in our source tree via `tox -evendor`. As such, we will never edit the code:
https://github.com/pantsbuild/pex/blob/80e00e0bc866d8aa2795391eef3daccadeb6d23f/pex/vendor/README.md#L1-L40

run isort on it:
https://github.com/pantsbuild/pex/blob/80e00e0bc866d8aa2795391eef3daccadeb6d23f/tox.ini#L116-L124
etc.

I'm going to close all these issues as won't fix. You might though try reporting these errors upstream to the vendored projects, namely setuptools, wheel and pip.
