### ISSUE TITLE
[Enhancement] Build missing wheels when platform tag is given

### ISSUE THREAD

**Issue by jhermann** [pantsbuild/pex#906]
When I tried to build a Windows PEX on Ubuntu, I had a problem with 'harmless' pure Python requirements, because PEX adds `--only-binary :all:` in that case – but many pure Python packages only have a sdist on PyPI.

See here for a solution:
https://github.com/jhermann/rituals/blob/f53f07189bb5df55fbb970c3aed8253726315b00/src/rituals/acts/releasing.py#L318-L324

This could possibly be integrated into PEX for a better user experience.

The other option is to have a wheel builder feed a local repo, but not everyone wants to run such infrastructure.

**Comment by jsirois** [comment]
This line is actually incorrect in the general case:
```python
ctx.run("python3 -m pip wheel -w dist/wheels -r requirements.txt .")
```

When run on Ubuntu, the `pip wheel` command will use the details of the Ubuntu python interpreter it's running under when solving the resolve graph. Since any distributions `install_requires` can have requirements like this (see: https://www.python.org/dev/peps/pep-0496):
```python
install_requires = [
  "win_fs_events==1.0.0; sys.platform == 'win32'",
  "unix_file_watcher==2.1.0; sys.platform == 'linux',"
]
```
The solution will be invalid for windows.

In other words, Pex could do this for a subset of cases but only if it knew enough about the resolve to verify the solution was valid for the target platform and if the sdists from that solution all plopped out wheels without a platform tag only (`none` or `any`). I can't see how Pex can do these things in any reasonable way that is always correct.

A similar question / concern comes in the comment here and my response: https://github.com/pantsbuild/pex/issues/733#issuecomment-570985584

**Comment by jsirois** [comment]
I'm going to close this as answered, but if you have further ideas on how Pex could do this correctly, please re-open and respond. I do agree that the user experience when building multiplatform pexes can be confusing and improvements here would be welcome.

**Comment by jhermann** [comment]
What this code does is build all the *none-any* wheels that are missing. Case at hand is PyYAML, I get the Windows wheel from PyPI. And the pure Python wheels that the "only-binary" causes to be essential (which they would not be without the option) come from the just created "dist/wheels" repository. In there is *also* PyYAML for the current platform, but it is ignored. End result is a set of wheels that satisfy *all* requirements in wheel-form, from either dist or PyPI.

And things suddenly work where they did not without pre-built wheels. :tada:

**Comment by jsirois** [comment]
Understood. Note though that environment markers allow ~anything to happen. They could be used to pull in PyYAML 1.0 for windows and 2.0 for linux. In that case you'd build the wrong version of the PyYAML sdist and not learn about this until runtime when use of an API that changed in 2.0 blew up.
